Forbidden Lands: rapidxml-1.13/rapidxml_utils.hpp File Reference
rapidxml_utils.hpp File Reference
#include "rapidxml.hpp"
#include <vector>
#include <string>
#include <fstream>
#include <stdexcept>
Classes
class rapidxml::file< Ch >
Represents data loaded from a file.
Functions
template<class Ch >
std::size_t rapidxml::count_children (xml_node< Ch > *node)
template<class Ch >
std::size_t rapidxml::count_attributes (xml_node< Ch > *node)
Detailed Description
This file contains high-level rapidxml utilities that can be useful in certain simple scenarios. They should probably not be used if maximizing performance is the main objective.
Function Documentation
count_attributes()
template<class Ch > std::size_t rapidxml::count_attributes (xml_node< Ch > * node) inline
Counts attributes of node. Time complexity is O(n).
Returns
Number of attributes of node
References rapidxml::count_attributes(), rapidxml::xml_node< Ch >::first_attribute(), and rapidxml::xml_attribute< Ch >::next_attribute().
Referenced by rapidxml::count_attributes().
count_children()
template<class Ch > std::size_t rapidxml::count_children (xml_node< Ch > * node) inline
Counts children of node. Time complexity is O(n).
Returns
Number of children of node
References rapidxml::count_children(), rapidxml::xml_node< Ch >::first_node(), and rapidxml::xml_node< Ch >::next_sibling().
Referenced by rapidxml::count_children().